# Generated by Django 5.1.1 on 2024-10-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_profile_department_profile_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
